#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseDataMappingModel
{
	
	
	/// <summary>
	/// Status of the DataMappingPowerBi
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AmPlc_DataMappingPowerBi_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0, null, null, null, 1033, "Active")]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1, null, null, null, 1033, "Inactive")]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the DataMappingPowerBi
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AmPlc_DataMappingPowerBi_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0, null, null, null, 1033, "Active")]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1, null, null, null, 1033, "Inactive")]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("amplc_datamappingpowerbi")]
	public partial class AmPlc_DataMappingPowerBi : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the amplc_datamappingpowerbi entity
		/// </summary>
		public partial class Fields
		{
			public const string AmPlc_ClassIdGuid = "amplc_classidguid";
			public const string AmpLc_DataMappingEntityForms_DataMappingPbI_AmpLc_DataMappingPowerBi = "AmpLc_DataMappingEntityForms_DataMappingPbI_AmpLc_DataMappingPowerBi";
			public const string AmPlc_DataMappingPowerBi_ProjectMarketingFAcTuRation_AmPlc_ProjectMarketingFAcTuRation = "amplc_datamappingpowerbi_projectmarketingfacturation_amplc_projectmarketingfacturation";
			public const string AmPlc_DataMappingPowerBiId = "amplc_datamappingpowerbiid";
			public const string Id = "amplc_datamappingpowerbiid";
			public const string AmPlc_Description = "amplc_description";
			public const string AmPlc_EmbeddedLinkPBi = "amplc_embeddedlinkpbi";
			public const string AmPlc_FilterAlias = "amplc_filteralias";
			public const string AmPlc_FilterAliasCir = "amplc_filteraliascir";
			public const string AmPlc_FilterAliasCir2 = "amplc_filteraliascir2";
			public const string AmPlc_FilterAliasComplaints = "amplc_filteraliascomplaints";
			public const string AmPlc_FilterAliasComplaints2 = "amplc_filteraliascomplaints2";
			public const string AmPlc_FilterAliasPor = "amplc_filteraliaspor";
			public const string AmPlc_FilterAliasPor2 = "amplc_filteraliaspor2";
			public const string AmPlc_FilterAliasSales = "amplc_filteraliassales";
			public const string AmPlc_FilterAliasSales2 = "amplc_filteraliassales2";
			public const string AmPlc_FilterAliasWcR = "amplc_filteraliaswcr";
			public const string AmPlc_FilterColumn = "amplc_filtercolumn";
			public const string AmPlc_FilterColumnCir = "amplc_filtercolumncir";
			public const string AmPlc_FilterColumnCir2 = "amplc_filtercolumncir2";
			public const string AmPlc_FilterColumnComplaints = "amplc_filtercolumncomplaints";
			public const string AmPlc_FilterColumnComplaints2 = "amplc_filtercolumncomplaints2";
			public const string AmPlc_FilterColumnPor = "amplc_filtercolumnpor";
			public const string AmPlc_FilterColumnPor2 = "amplc_filtercolumnpor2";
			public const string AmPlc_FilterColumnSales = "amplc_filtercolumnsales";
			public const string AmPlc_FilterColumnSales2 = "amplc_filtercolumnsales2";
			public const string AmPlc_FilterColumnWcR = "amplc_filtercolumnwcr";
			public const string AmPlc_FilterTable = "amplc_filtertable";
			public const string AmPlc_FilterTableCir = "amplc_filtertablecir";
			public const string AmPlc_FilterTableCir2 = "amplc_filtertablecir2";
			public const string AmPlc_FilterTableComplaints = "amplc_filtertablecomplaints";
			public const string AmPlc_FilterTableComplaints2 = "amplc_filtertablecomplaints2";
			public const string AmPlc_FilterTablePor = "amplc_filtertablepor";
			public const string AmPlc_FilterTablePor2 = "amplc_filtertablepor2";
			public const string AmPlc_FilterTableSales = "amplc_filtertablesales";
			public const string AmPlc_FilterTableSales2 = "amplc_filtertablesales2";
			public const string AmPlc_FilterTableWcR = "amplc_filtertablewcr";
			public const string AmPlc_ModificationDateCir = "amplc_modificationdatecir";
			public const string AmPlc_ModificationDateComplaints = "amplc_modificationdatecomplaints";
			public const string AmPlc_ModificationDateCSr = "amplc_modificationdatecsr";
			public const string AmPlc_ModificationDatePor = "amplc_modificationdatepor";
			public const string AmPlc_ModificationDateSales = "amplc_modificationdatesales";
			public const string AmPlc_ModificationDateWcR = "amplc_modificationdatewcr";
			public const string AmPlc_Name = "amplc_name";
			public const string AmPlc_ProjectMarketingFAcTuRation = "amplc_projectmarketingfacturation";
			public const string AmPlc_ProjectMarketingFAcTuRationName = "amplc_projectmarketingfacturationname";
			public const string AmPlc_ReportGUIdCir = "amplc_reportguidcir";
			public const string AmPlc_ReportGUIdCirSoldTo = "amplc_reportguidcirsoldto";
			public const string AmPlc_ReportGUIdComplaints = "amplc_reportguidcomplaints";
			public const string AmPlc_ReportGUIdCSr = "amplc_reportguidcsr";
			public const string AmPlc_ReportGUIdPor = "amplc_reportguidpor";
			public const string AmPlc_ReportGUIdSales = "amplc_reportguidsales";
			public const string AmPlc_ReportGUIdWcR = "amplc_reportguidwcr";
			public const string AmPlc_ReportNameCir = "amplc_reportnamecir";
			public const string AmPlc_ReportNameCirSoldTo = "amplc_reportnamecirsoldto";
			public const string AmPlc_ReportNameComplaints = "amplc_reportnamecomplaints";
			public const string AmPlc_ReportNameCSr = "amplc_reportnamecsr";
			public const string AmPlc_ReportNamePor = "amplc_reportnamepor";
			public const string AmPlc_ReportNameSales = "amplc_reportnamesales";
			public const string AmPlc_ReportNameWcR = "amplc_reportnamewcr";
			public const string AmPlc_TenantIdGuid = "amplc_tenantidguid";
			public const string AmPlc_WorkspacePBiGuid = "amplc_workspacepbiguid";
			public const string AmPlc_WorkspacePBigUIdPrepRod = "amplc_workspacepbiguidpreprod";
			public const string AmPlc_WorkspacePowerBi = "amplc_workspacepowerbi";
			public const string AmPlc_WorkspacePowerBiDev = "amplc_workspacepowerbidev";
			public const string AmPlc_WorkspacePowerBigUIdDev = "amplc_workspacepowerbiguiddev";
			public const string AmPlc_WorkspacePowerBiPrepRod = "amplc_workspacepowerbipreprod";
			public const string Business_Unit_AmPlc_DataMappingPowerBi = "business_unit_amplc_datamappingpowerbi";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string Lk_AmPlc_DataMappingPowerBi_CreatedBy = "lk_amplc_datamappingpowerbi_createdby";
			public const string Lk_AmPlc_DataMappingPowerBi_CreatedOnBehalfBy = "lk_amplc_datamappingpowerbi_createdonbehalfby";
			public const string Lk_AmPlc_DataMappingPowerBi_ModifiedBy = "lk_amplc_datamappingpowerbi_modifiedby";
			public const string Lk_AmPlc_DataMappingPowerBi_ModifiedOnBehalfBy = "lk_amplc_datamappingpowerbi_modifiedonbehalfby";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StateCodename = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodename = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string User_AmPlc_DataMappingPowerBi = "user_amplc_datamappingpowerbi";
			public const string UtcConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public AmPlc_DataMappingPowerBi(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public AmPlc_DataMappingPowerBi(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public AmPlc_DataMappingPowerBi(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public AmPlc_DataMappingPowerBi() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "amplc_datamappingpowerbiid";
		
		public const string PrimaryNameAttribute = "amplc_name";
		
		public const string EntitySchemaName = "amplc_DataMappingPowerBi";
		
		public const string EntityLogicalName = "amplc_datamappingpowerbi";
		
		public const string EntityLogicalCollectionName = "amplc_datamappingpowerbis";
		
		public const string EntitySetName = "amplc_datamappingpowerbis";
		
		public const int EntityTypeCode = 11130;
		
		/// <summary>
		/// Guid Classid in the customizations.xml for the control containing the Power BI data.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_classidguid")]
		public string AmPlc_ClassIdGuid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_classidguid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_classidguid", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_datamappingpowerbiid")]
		public System.Nullable<System.Guid> AmPlc_DataMappingPowerBiId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("amplc_datamappingpowerbiid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_datamappingpowerbiid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_datamappingpowerbiid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.AmPlc_DataMappingPowerBiId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_description")]
		public string AmPlc_Description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_description", value);
			}
		}
		
		/// <summary>
		/// embedded link from PBI for the report.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_embeddedlinkpbi")]
		public string AmPlc_EmbeddedLinkPBi
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_embeddedlinkpbi");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_embeddedlinkpbi", value);
			}
		}
		
		/// <summary>
		/// Used to pass as an alias the power BI XML; for the filter column.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filteralias")]
		public string AmPlc_FilterAlias
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filteralias");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filteralias", value);
			}
		}
		
		/// <summary>
		/// Alias for the filter in the report in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filteraliascir")]
		public string AmPlc_FilterAliasCir
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filteraliascir");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filteraliascir", value);
			}
		}
		
		/// <summary>
		/// Dataverse field for the customer group account.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filteraliascir2")]
		public string AmPlc_FilterAliasCir2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filteraliascir2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filteraliascir2", value);
			}
		}
		
		/// <summary>
		/// Alias for the report complaints in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filteraliascomplaints")]
		public string AmPlc_FilterAliasComplaints
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filteraliascomplaints");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filteraliascomplaints", value);
			}
		}
		
		/// <summary>
		/// Alias for sold to account.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filteraliascomplaints2")]
		public string AmPlc_FilterAliasComplaints2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filteraliascomplaints2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filteraliascomplaints2", value);
			}
		}
		
		/// <summary>
		/// alias for the report purchased orders in PBI.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filteraliaspor")]
		public string AmPlc_FilterAliasPor
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filteraliaspor");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filteraliaspor", value);
			}
		}
		
		/// <summary>
		/// Alias for sold to account.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filteraliaspor2")]
		public string AmPlc_FilterAliasPor2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filteraliaspor2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filteraliaspor2", value);
			}
		}
		
		/// <summary>
		/// Filter Alias for the sales report in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filteraliassales")]
		public string AmPlc_FilterAliasSales
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filteraliassales");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filteraliassales", value);
			}
		}
		
		/// <summary>
		/// Alias for sold to account.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filteraliassales2")]
		public string AmPlc_FilterAliasSales2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filteraliassales2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filteraliassales2", value);
			}
		}
		
		/// <summary>
		/// Alias for the report WCR in PBI.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filteraliaswcr")]
		public string AmPlc_FilterAliasWcR
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filteraliaswcr");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filteraliaswcr", value);
			}
		}
		
		/// <summary>
		/// Filter used for the column to pass the accountNumber of the account in the report.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtercolumn")]
		public string AmPlc_FilterColumn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtercolumn");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtercolumn", value);
			}
		}
		
		/// <summary>
		/// Filter column for the report CIR in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtercolumncir")]
		public string AmPlc_FilterColumnCir
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtercolumncir");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtercolumncir", value);
			}
		}
		
		/// <summary>
		/// Column for the customer groups account
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtercolumncir2")]
		public string AmPlc_FilterColumnCir2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtercolumncir2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtercolumncir2", value);
			}
		}
		
		/// <summary>
		/// Filter column for the report complaints in PBI.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtercolumncomplaints")]
		public string AmPlc_FilterColumnComplaints
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtercolumncomplaints");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtercolumncomplaints", value);
			}
		}
		
		/// <summary>
		/// Column for sold to account.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtercolumncomplaints2")]
		public string AmPlc_FilterColumnComplaints2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtercolumncomplaints2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtercolumncomplaints2", value);
			}
		}
		
		/// <summary>
		/// Filter column for the report POR in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtercolumnpor")]
		public string AmPlc_FilterColumnPor
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtercolumnpor");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtercolumnpor", value);
			}
		}
		
		/// <summary>
		/// Column for cold to account.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtercolumnpor2")]
		public string AmPlc_FilterColumnPor2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtercolumnpor2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtercolumnpor2", value);
			}
		}
		
		/// <summary>
		/// filter column for the sales report in PBI.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtercolumnsales")]
		public string AmPlc_FilterColumnSales
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtercolumnsales");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtercolumnsales", value);
			}
		}
		
		/// <summary>
		/// Column for sold to account.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtercolumnsales2")]
		public string AmPlc_FilterColumnSales2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtercolumnsales2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtercolumnsales2", value);
			}
		}
		
		/// <summary>
		/// Filter column for the report WCR in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtercolumnwcr")]
		public string AmPlc_FilterColumnWcR
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtercolumnwcr");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtercolumnwcr", value);
			}
		}
		
		/// <summary>
		/// Used in the XML cusotmizations.xml to filter using accountnumber field of CRM.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtertable")]
		public string AmPlc_FilterTable
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtertable");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtertable", value);
			}
		}
		
		/// <summary>
		/// Filter table for the report CIR
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtertablecir")]
		public string AmPlc_FilterTableCir
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtertablecir");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtertablecir", value);
			}
		}
		
		/// <summary>
		/// For the Account as Customer Group
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtertablecir2")]
		public string AmPlc_FilterTableCir2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtertablecir2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtertablecir2", value);
			}
		}
		
		/// <summary>
		/// Filter table for the report Complaints
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtertablecomplaints")]
		public string AmPlc_FilterTableComplaints
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtertablecomplaints");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtertablecomplaints", value);
			}
		}
		
		/// <summary>
		/// Table for sold to account.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtertablecomplaints2")]
		public string AmPlc_FilterTableComplaints2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtertablecomplaints2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtertablecomplaints2", value);
			}
		}
		
		/// <summary>
		/// Filter table for purchased orders report in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtertablepor")]
		public string AmPlc_FilterTablePor
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtertablepor");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtertablepor", value);
			}
		}
		
		/// <summary>
		/// Table for sold to account.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtertablepor2")]
		public string AmPlc_FilterTablePor2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtertablepor2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtertablepor2", value);
			}
		}
		
		/// <summary>
		/// Filter table for the sales report in PBI.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtertablesales")]
		public string AmPlc_FilterTableSales
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtertablesales");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtertablesales", value);
			}
		}
		
		/// <summary>
		/// Table for the sold to account.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtertablesales2")]
		public string AmPlc_FilterTableSales2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtertablesales2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtertablesales2", value);
			}
		}
		
		/// <summary>
		/// Filter Table for the report WCR in PBI.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_filtertablewcr")]
		public string AmPlc_FilterTableWcR
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_filtertablewcr");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_filtertablewcr", value);
			}
		}
		
		/// <summary>
		/// Modification data for the report in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_modificationdatecir")]
		public System.Nullable<System.DateTime> AmPlc_ModificationDateCir
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("amplc_modificationdatecir");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_modificationdatecir", value);
			}
		}
		
		/// <summary>
		/// Modification data for the report Complaints in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_modificationdatecomplaints")]
		public System.Nullable<System.DateTime> AmPlc_ModificationDateComplaints
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("amplc_modificationdatecomplaints");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_modificationdatecomplaints", value);
			}
		}
		
		/// <summary>
		/// Modification date for the report CSR
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_modificationdatecsr")]
		public System.Nullable<System.DateTime> AmPlc_ModificationDateCSr
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("amplc_modificationdatecsr");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_modificationdatecsr", value);
			}
		}
		
		/// <summary>
		/// Modification data for the report in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_modificationdatepor")]
		public System.Nullable<System.DateTime> AmPlc_ModificationDatePor
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("amplc_modificationdatepor");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_modificationdatepor", value);
			}
		}
		
		/// <summary>
		/// Modification date for the sales report in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_modificationdatesales")]
		public System.Nullable<System.DateTime> AmPlc_ModificationDateSales
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("amplc_modificationdatesales");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_modificationdatesales", value);
			}
		}
		
		/// <summary>
		/// Modification data for the report WCR in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_modificationdatewcr")]
		public System.Nullable<System.DateTime> AmPlc_ModificationDateWcR
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("amplc_modificationdatewcr");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_modificationdatewcr", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_name")]
		public string AmPlc_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_name", value);
			}
		}
		
		/// <summary>
		/// Project of the marketing-facturation department
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_projectmarketingfacturation")]
		public Microsoft.Xrm.Sdk.EntityReference AmPlc_ProjectMarketingFAcTuRation
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("amplc_projectmarketingfacturation");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_projectmarketingfacturation", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_projectmarketingfacturationname")]
		public string AmPlc_ProjectMarketingFAcTuRationName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("amplc_projectmarketingfacturation"))
				{
					return this.FormattedValues["amplc_projectmarketingfacturation"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Guid of the report in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportguidcir")]
		public string AmPlc_ReportGUIdCir
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportguidcir");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportguidcir", value);
			}
		}
		
		/// <summary>
		/// Guid of the report for SoldTo
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportguidcirsoldto")]
		public string AmPlc_ReportGUIdCirSoldTo
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportguidcirsoldto");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportguidcirsoldto", value);
			}
		}
		
		/// <summary>
		/// Guid of the report in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportguidcomplaints")]
		public string AmPlc_ReportGUIdComplaints
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportguidcomplaints");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportguidcomplaints", value);
			}
		}
		
		/// <summary>
		/// Guid of the report in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportguidcsr")]
		public string AmPlc_ReportGUIdCSr
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportguidcsr");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportguidcsr", value);
			}
		}
		
		/// <summary>
		/// Guid of the report purchased orders in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportguidpor")]
		public string AmPlc_ReportGUIdPor
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportguidpor");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportguidpor", value);
			}
		}
		
		/// <summary>
		/// Guid of the report Sales
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportguidsales")]
		public string AmPlc_ReportGUIdSales
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportguidsales");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportguidsales", value);
			}
		}
		
		/// <summary>
		/// Guid of the report WCR in PBI.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportguidwcr")]
		public string AmPlc_ReportGUIdWcR
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportguidwcr");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportguidwcr", value);
			}
		}
		
		/// <summary>
		/// Name of the report CIR in PBI.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportnamecir")]
		public string AmPlc_ReportNameCir
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportnamecir");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportnamecir", value);
			}
		}
		
		/// <summary>
		/// report for sold to account.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportnamecirsoldto")]
		public string AmPlc_ReportNameCirSoldTo
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportnamecirsoldto");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportnamecirsoldto", value);
			}
		}
		
		/// <summary>
		/// Name of the complaints report in PBI.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportnamecomplaints")]
		public string AmPlc_ReportNameComplaints
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportnamecomplaints");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportnamecomplaints", value);
			}
		}
		
		/// <summary>
		/// Name of the report for Customer Satifaction report in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportnamecsr")]
		public string AmPlc_ReportNameCSr
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportnamecsr");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportnamecsr", value);
			}
		}
		
		/// <summary>
		/// Name of the report Purchase orders in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportnamepor")]
		public string AmPlc_ReportNamePor
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportnamepor");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportnamepor", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportnamesales")]
		public string AmPlc_ReportNameSales
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportnamesales");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportnamesales", value);
			}
		}
		
		/// <summary>
		/// Name of the report Wire Carrier in PBI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_reportnamewcr")]
		public string AmPlc_ReportNameWcR
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_reportnamewcr");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_reportnamewcr", value);
			}
		}
		
		/// <summary>
		/// Tenant Guid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_tenantidguid")]
		public string AmPlc_TenantIdGuid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_tenantidguid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_tenantidguid", value);
			}
		}
		
		/// <summary>
		/// the guid used in REST API
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_workspacepbiguid")]
		public string AmPlc_WorkspacePBiGuid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_workspacepbiguid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_workspacepbiguid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_workspacepbiguidpreprod")]
		public string AmPlc_WorkspacePBigUIdPrepRod
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_workspacepbiguidpreprod");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_workspacepbiguidpreprod", value);
			}
		}
		
		/// <summary>
		/// The name of workspace in Power BI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_workspacepowerbi")]
		public string AmPlc_WorkspacePowerBi
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_workspacepowerbi");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_workspacepowerbi", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_workspacepowerbidev")]
		public string AmPlc_WorkspacePowerBiDev
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_workspacepowerbidev");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_workspacepowerbidev", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_workspacepowerbiguiddev")]
		public string AmPlc_WorkspacePowerBigUIdDev
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_workspacepowerbiguiddev");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_workspacepowerbiguiddev", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_workspacepowerbipreprod")]
		public string AmPlc_WorkspacePowerBiPrepRod
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amplc_workspacepowerbipreprod");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("amplc_workspacepowerbipreprod", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("createdonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("modifiedonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the DataMappingPowerBi
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual AmPlc_DataMappingPowerBi_StateCode? StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((AmPlc_DataMappingPowerBi_StateCode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string StateCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the DataMappingPowerBi
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual AmPlc_DataMappingPowerBi_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((AmPlc_DataMappingPowerBi_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string StatusCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UtcConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N amplc_datamappingentityforms_datamappingpbi_amplc_datamappingpowerbi
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("amplc_datamappingentityforms_datamappingpbi_amplc_datamappingpowerbi")]
		public System.Collections.Generic.IEnumerable<DataverseDataMappingModel.AmPlc_DataMappingEntityForms> AmpLc_DataMappingEntityForms_DataMappingPbI_AmpLc_DataMappingPowerBi
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseDataMappingModel.AmPlc_DataMappingEntityForms>("amplc_datamappingentityforms_datamappingpbi_amplc_datamappingpowerbi", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseDataMappingModel.AmPlc_DataMappingEntityForms>("amplc_datamappingentityforms_datamappingpbi_amplc_datamappingpowerbi", null, value);
			}
		}
		
		/// <summary>
		/// N:1 amplc_datamappingpowerbi_projectmarketingfacturation_amplc_projectmarketingfacturation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amplc_projectmarketingfacturation")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("amplc_datamappingpowerbi_projectmarketingfacturation_amplc_projectmarketingfactur" +
			"ation")]
		public DataverseDataMappingModel.AmPlc_ProjectMarketingFAcTuRation AmPlc_DataMappingPowerBi_ProjectMarketingFAcTuRation_AmPlc_ProjectMarketingFAcTuRation
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseDataMappingModel.AmPlc_ProjectMarketingFAcTuRation>("amplc_datamappingpowerbi_projectmarketingfacturation_amplc_projectmarketingfactur" +
						"ation", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseDataMappingModel.AmPlc_ProjectMarketingFAcTuRation>("amplc_datamappingpowerbi_projectmarketingfacturation_amplc_projectmarketingfactur" +
						"ation", null, value);
			}
		}
		
		/// <summary>
		/// N:1 business_unit_amplc_datamappingpowerbi
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_amplc_datamappingpowerbi")]
		public DataverseDataMappingModel.BusinessUnit Business_Unit_AmPlc_DataMappingPowerBi
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseDataMappingModel.BusinessUnit>("business_unit_amplc_datamappingpowerbi", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_amplc_datamappingpowerbi_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_amplc_datamappingpowerbi_createdby")]
		public DataverseDataMappingModel.SystemUser Lk_AmPlc_DataMappingPowerBi_CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseDataMappingModel.SystemUser>("lk_amplc_datamappingpowerbi_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_amplc_datamappingpowerbi_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_amplc_datamappingpowerbi_createdonbehalfby")]
		public DataverseDataMappingModel.SystemUser Lk_AmPlc_DataMappingPowerBi_CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseDataMappingModel.SystemUser>("lk_amplc_datamappingpowerbi_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseDataMappingModel.SystemUser>("lk_amplc_datamappingpowerbi_createdonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_amplc_datamappingpowerbi_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_amplc_datamappingpowerbi_modifiedby")]
		public DataverseDataMappingModel.SystemUser Lk_AmPlc_DataMappingPowerBi_ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseDataMappingModel.SystemUser>("lk_amplc_datamappingpowerbi_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_amplc_datamappingpowerbi_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_amplc_datamappingpowerbi_modifiedonbehalfby")]
		public DataverseDataMappingModel.SystemUser Lk_AmPlc_DataMappingPowerBi_ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseDataMappingModel.SystemUser>("lk_amplc_datamappingpowerbi_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseDataMappingModel.SystemUser>("lk_amplc_datamappingpowerbi_modifiedonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 user_amplc_datamappingpowerbi
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_amplc_datamappingpowerbi")]
		public DataverseDataMappingModel.SystemUser User_AmPlc_DataMappingPowerBi
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseDataMappingModel.SystemUser>("user_amplc_datamappingpowerbi", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public AmPlc_DataMappingPowerBi(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["amplc_datamappingpowerbiid"] = base.Id;
                        break;
                    case "amplc_datamappingpowerbiid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
