#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

//[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace DataverseDataMappingModel
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class DataverseDataMappingContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public DataverseDataMappingContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.ActivityParty"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.ActivityParty> ActivityPartySet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.ActivityParty>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.ActivityPointer"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.ActivityPointer> ActivityPointerSet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.ActivityPointer>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.AmPlc_DataMappingEntityForms"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.AmPlc_DataMappingEntityForms> AmPlc_DataMappingEntityFormsSet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.AmPlc_DataMappingEntityForms>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.AmPlc_DataMappingPowerBi"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.AmPlc_DataMappingPowerBi> AmPlc_DataMappingPowerBiSet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.AmPlc_DataMappingPowerBi>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.AmPlc_ProjectMarketingFAcTuRation"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.AmPlc_ProjectMarketingFAcTuRation> AmPlc_ProjectMarketingFAcTuRationSet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.AmPlc_ProjectMarketingFAcTuRation>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.BusinessUnit"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.BusinessUnit> BusinessUnitSet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.BusinessUnit>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.Email"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.Email> EmailSet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.Email>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.Solution"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.Solution> SolutionSet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.Solution>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.SolutionComponent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.SolutionComponent> SolutionComponentSet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.SolutionComponent>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.SolutionHistoryData"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.SolutionHistoryData> SolutionHistoryDataSet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.SolutionHistoryData>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.SystemForm"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.SystemForm> SystemFormSet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.SystemForm>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.SystemUser> SystemUserSet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.SystemUser>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="DataverseDataMappingModel.TransactionCurrency"/> entities.
		/// </summary>
		public System.Linq.IQueryable<DataverseDataMappingModel.TransactionCurrency> TransactionCurrencySet
		{
			get
			{
				return this.CreateQuery<DataverseDataMappingModel.TransactionCurrency>();
			}
		}
	}
	
	/// <summary>
	/// Attribute to handle storing the OptionSet's Metadata.
	/// </summary>
	[System.AttributeUsageAttribute(System.AttributeTargets.Field)]
	public sealed class OptionSetMetadataAttribute : System.Attribute
	{
		
		private object[] _nameObjects;
		
		private System.Collections.Generic.Dictionary<int, string> _names;
		
		/// <summary>
		/// Color of the OptionSetValue.
		/// </summary>
		public string Color { get; set; }
		
		/// <summary>
		/// Description of the OptionSetValue.
		/// </summary>
		public string Description { get; set; }
		
		/// <summary>
		/// Display order index of the OptionSetValue.
		/// </summary>
		public int DisplayIndex { get; set; }
		
		/// <summary>
		/// External value of the OptionSetValue.
		/// </summary>
		public string ExternalValue { get; set; }
		
		/// <summary>
		/// Name of the OptionSetValue.
		/// </summary>
		public string Name { get; set; }
		
		/// <summary>
		/// Names of the OptionSetValue.
		/// </summary>
		public System.Collections.Generic.Dictionary<int, string> Names
		{
			get
			{
				return _names ?? (_names = CreateNames());
			} 
			set
			{
				_names = value;
				if (value == null)
				{
				    _nameObjects = new object[0];
				}
				else
				{
				    _nameObjects = null;
				}
			}
		}
		
		/// <summary>
		/// Initializes a new instance of the <see cref="OptionSetMetadataAttribute"/> class.
		/// </summary>
		/// <param name="name">Name of the value.</param>
		/// <param name="displayIndex">Display order index of the value.</param>
		/// <param name="color">Color of the value.</param>
		/// <param name="description">Description of the value.</param>
		/// <param name="externalValue">External value of the value.</param>
		/// <param name="names">Names of the value.</param>
		public OptionSetMetadataAttribute(string name, int displayIndex, string color = null, string description = null, string externalValue = null, params object[] names)
		{
			this.Color = color;
			this.Description = description;
			this._nameObjects = names;
			this.ExternalValue = externalValue;
			this.DisplayIndex = displayIndex;
			this.Name = name;
		}
		
		private System.Collections.Generic.Dictionary<int, string> CreateNames()
		{
			System.Collections.Generic.Dictionary<int, string> names = new System.Collections.Generic.Dictionary<int, string>();
			for (int i = 0; (i < _nameObjects.Length); i = (i + 2))
			{
				names.Add(((int)(_nameObjects[i])), ((string)(_nameObjects[(i + 1)])));
			}
			return names;
		}
	}
	
	/// <summary>
	/// Extension class to handle retrieving of OptionSetMetadataAttribute.
	/// </summary>
	public static class OptionSetExtension
	{
		
		/// <summary>
		/// Returns the OptionSetMetadataAttribute for the given enum value
		/// </summary>
		/// <typeparam name="T">OptionSet Enum Type</typeparam>
		/// <param name="value">Enum Value with OptionSetMetadataAttribute</param>
		public static OptionSetMetadataAttribute GetMetadata<T>(this T value)
			where T :  struct, System.IConvertible
		{
			System.Type enumType = typeof(T);
			if (!enumType.IsEnum)
			{
				throw new System.ArgumentException("T must be an enum!");
			}
			System.Reflection.MemberInfo[] members = enumType.GetMember(value.ToString());
			for (int i = 0; (i < members.Length); i++
			)
			{
				System.Attribute attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(members[i], typeof(OptionSetMetadataAttribute));
				if (attribute != null)
				{
					return ((OptionSetMetadataAttribute)(attribute));
				}
			}
			throw new System.ArgumentException("T must be an enum adorned with an OptionSetMetadataAttribute!");
		}
	}
}
#pragma warning restore CS1591
