#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseDataMappingModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum AmPlc_TypeOfMainForm
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Main", 2, "#038028", "", "", 1033, "Main")]
		Main = 420750002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("N/A", 0, "#f7a8a8", "", "", 1033, "N/A")]
		NA = 420750000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Principal", 1, "#027d15", "", "", 1033, "Principal")]
		Principal = 420750001,
	}
}
#pragma warning restore CS1591
