#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseDataMappingModel
{
	
	
	/// <summary>
	/// All of the possible component types for solutions.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ComponentType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AI Configuration", 86, null, null, null, 1033, "AI Configuration")]
		AiConfiguration = 402,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AI Project", 85, null, null, null, 1033, "AI Project")]
		AiProject = 401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AI Project Type", 84, null, null, null, 1033, "AI Project Type")]
		AiProjectType = 400,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Attachment", 28, null, null, null, 1033, "Attachment")]
		Attachment = 35,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Attribute", 1, null, null, null, 1033, "Attribute")]
		Attribute = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Attribute Image Configuration", 88, null, null, null, 1033, "Attribute Image Configuration")]
		AttributeImageConfiguration = 431,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Attribute Lookup Value", 4, null, null, null, 1033, "Attribute Lookup Value")]
		AttributeLookupValue = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Attribute Map", 36, null, null, null, 1033, "Attribute Map")]
		AttributeMap = 47,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Attribute Picklist Value", 3, null, null, null, 1033, "Attribute Picklist Value")]
		AttributePicklistValue = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Canvas App", 79, null, null, null, 1033, "Canvas App")]
		CanvasApp = 300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Complex Control", 48, null, null, null, 1033, "Complex Control")]
		ComplexControl = 64,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Connection Role", 47, null, null, null, 1033, "Connection Role")]
		ConnectionRole = 63,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Connector", 80, null, null, null, 1033, "Connector")]
		Connector_371 = 371,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Connector", 81, null, null, null, 1033, "Connector")]
		Connector_372 = 372,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Contract Template", 30, null, null, null, 1033, "Contract Template")]
		ContractTemplate = 37,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Convert Rule", 60, null, null, null, 1033, "Convert Rule")]
		ConvertRule = 154,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Convert Rule Item", 61, null, null, null, 1033, "Convert Rule Item")]
		ConvertRuleItem = 155,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Custom Control", 66, null, null, null, 1033, "Custom Control")]
		CustomControl = 66,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Custom Control Default Config", 67, null, null, null, 1033, "Custom Control Default Config")]
		CustomControlDefaultConfig = 68,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Data Source Mapping", 68, null, null, null, 1033, "Data Source Mapping")]
		DataSourceMapping = 166,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Display String", 18, null, null, null, 1033, "Display String")]
		DisplayString = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Display String Map", 19, null, null, null, 1033, "Display String Map")]
		DisplayStringMap = 23,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Duplicate Rule", 33, null, null, null, 1033, "Duplicate Rule")]
		DuplicateRule = 44,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Duplicate Rule Condition", 34, null, null, null, 1033, "Duplicate Rule Condition")]
		DuplicateRuleCondition = 45,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email Template", 29, null, null, null, 1033, "Email Template")]
		EmailTemplate = 36,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entity", 0, null, null, null, 1033, "Entity")]
		Entity = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entity Analytics Configuration", 87, null, null, null, 1033, "Entity Analytics Configuration")]
		EntityAnalyticsConfiguration = 430,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entity Image Configuration", 89, null, null, null, 1033, "Entity Image Configuration")]
		EntityImageConfiguration = 432,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entity Key", 13, null, null, null, 1033, "Entity Key")]
		EntityKey = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entity Map", 35, null, null, null, 1033, "Entity Map")]
		EntityMap = 46,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entity Relationship", 9, null, null, null, 1033, "Entity Relationship")]
		EntityRelationship = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entity Relationship Relationships", 11, null, null, null, 1033, "Entity Relationship Relationships")]
		EntityRelationshipRelationships = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entity Relationship Role", 10, null, null, null, 1033, "Entity Relationship Role")]
		EntityRelationshipRole = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Environment Variable Definition", 82, null, null, null, 1033, "Environment Variable Definition")]
		EnvironmentVariableDefinition = 380,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Environment Variable Value", 83, null, null, null, 1033, "Environment Variable Value")]
		EnvironmentVariableValue = 381,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Field Permission", 50, null, null, null, 1033, "Field Permission")]
		FieldPermission = 71,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Field Security Profile", 49, null, null, null, 1033, "Field Security Profile")]
		FieldSecurityProfile = 70,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Form", 20, null, null, null, 1033, "Form")]
		Form = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hierarchy Rule", 62, null, null, null, 1033, "Hierarchy Rule")]
		HierarchyRule = 65,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Import Map", 78, null, null, null, 1033, "Import Map")]
		ImportMap = 208,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Index", 77, null, null, null, 1033, "Index")]
		Index = 18,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("KB Article Template", 31, null, null, null, 1033, "KB Article Template")]
		KbArticleTemplate = 38,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Localized Label", 6, null, null, null, 1033, "Localized Label")]
		LocalizedLabel = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mail Merge Template", 32, null, null, null, 1033, "Mail Merge Template")]
		MailMergeTemplate = 39,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Managed Property", 12, null, null, null, 1033, "Managed Property")]
		ManagedProperty = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mobile Offline Profile", 63, null, null, null, 1033, "Mobile Offline Profile")]
		MobileOfflineProfile = 161,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mobile Offline Profile Item", 64, null, null, null, 1033, "Mobile Offline Profile Item")]
		MobileOfflineProfileItem = 162,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Option Set", 8, null, null, null, 1033, "Option Set")]
		OptionSet = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Organization", 21, null, null, null, 1033, "Organization")]
		Organization = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Plugin Assembly", 52, null, null, null, 1033, "Plugin Assembly")]
		PluginAssembly = 91,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Plugin Type", 51, null, null, null, 1033, "Plugin Type")]
		PluginType = 90,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Privilege", 14, null, null, null, 1033, "Privilege")]
		Privilege = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PrivilegeObjectTypeCode", 15, null, null, null, 1033, "PrivilegeObjectTypeCode")]
		Privilegeobjecttypecode = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Relationship", 2, null, null, null, 1033, "Relationship")]
		Relationship = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Relationship Extra Condition", 7, null, null, null, 1033, "Relationship Extra Condition")]
		RelationshipExtraCondition = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Report", 24, null, null, null, 1033, "Report")]
		Report = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Report Category", 26, null, null, null, 1033, "Report Category")]
		ReportCategory = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Report Entity", 25, null, null, null, 1033, "Report Entity")]
		ReportEntity = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Report Visibility", 27, null, null, null, 1033, "Report Visibility")]
		ReportVisibility = 34,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ribbon Command", 37, null, null, null, 1033, "Ribbon Command")]
		RibbonCommand = 48,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ribbon Context Group", 38, null, null, null, 1033, "Ribbon Context Group")]
		RibbonContextGroup = 49,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ribbon Customization", 39, null, null, null, 1033, "Ribbon Customization")]
		RibbonCustomization = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ribbon Diff", 42, null, null, null, 1033, "Ribbon Diff")]
		RibbonDiff = 55,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ribbon Rule", 40, null, null, null, 1033, "Ribbon Rule")]
		RibbonRule = 52,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ribbon Tab To Command Map", 41, null, null, null, 1033, "Ribbon Tab To Command Map")]
		RibbonTabToCommandMap = 53,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Role", 16, null, null, null, 1033, "Role")]
		Role = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Role Privilege", 17, null, null, null, 1033, "Role Privilege")]
		RolePrivilege = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Routing Rule", 56, null, null, null, 1033, "Routing Rule")]
		RoutingRule = 150,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Routing Rule Item", 57, null, null, null, 1033, "Routing Rule Item")]
		RoutingRuleItem = 151,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Saved Query", 22, null, null, null, 1033, "Saved Query")]
		SavedQuery = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Saved Query Visualization", 43, null, null, null, 1033, "Saved Query Visualization")]
		SavedQueryVisualization = 59,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SDKMessage", 69, null, null, null, 1033, "SDKMessage")]
		Sdkmessage = 201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SDKMessageFilter", 70, null, null, null, 1033, "SDKMessageFilter")]
		Sdkmessagefilter = 202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SdkMessagePair", 71, null, null, null, 1033, "SdkMessagePair")]
		Sdkmessagepair = 203,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SDK Message Processing Step", 53, null, null, null, 1033, "SDK Message Processing Step")]
		SdkMessageProcessingStep = 92,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SDK Message Processing Step Image", 54, null, null, null, 1033, "SDK Message Processing Step Image")]
		SdkMessageProcessingStepImage = 93,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SdkMessageRequest", 72, null, null, null, 1033, "SdkMessageRequest")]
		Sdkmessagerequest = 204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SdkMessageRequestField", 73, null, null, null, 1033, "SdkMessageRequestField")]
		Sdkmessagerequestfield = 205,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SdkMessageResponse", 74, null, null, null, 1033, "SdkMessageResponse")]
		Sdkmessageresponse = 206,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SdkMessageResponseField", 75, null, null, null, 1033, "SdkMessageResponseField")]
		Sdkmessageresponsefield = 207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Service Endpoint", 55, null, null, null, 1033, "Service Endpoint")]
		ServiceEndpoint = 95,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Similarity Rule", 65, null, null, null, 1033, "Similarity Rule")]
		SimilarityRule = 165,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Site Map", 46, null, null, null, 1033, "Site Map")]
		SiteMap = 62,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SLA", 58, null, null, null, 1033, "SLA")]
		Sla = 152,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SLA Item", 59, null, null, null, 1033, "SLA Item")]
		SlaItem = 153,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("System Form", 44, null, null, null, 1033, "System Form")]
		SystemForm = 60,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("View Attribute", 5, null, null, null, 1033, "View Attribute")]
		ViewAttribute = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Resource", 45, null, null, null, 1033, "Web Resource")]
		WebResource = 61,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WebWizard", 76, null, null, null, 1033, "WebWizard")]
		Webwizard = 210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Workflow", 23, null, null, null, 1033, "Workflow")]
		Workflow = 29,
	}
}
#pragma warning restore CS1591
