#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseDataMappingModel
{
	
	
	/// <summary>
	/// Categories for connection roles.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ConnectionRole_Category
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Business", 0, null, null, null, 1033, "Business")]
		Business = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Family", 1, null, null, null, 1033, "Family")]
		Family = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 4, null, null, null, 1033, "Other")]
		Other = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sales", 3, null, null, null, 1033, "Sales")]
		Sales = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sales Team", 6, null, null, null, 1033, "Sales Team")]
		SalesTeam = 1001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Service", 7, null, null, null, 1033, "Service")]
		Service = 1002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Social", 2, null, null, null, 1033, "Social")]
		Social = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Stakeholder", 5, null, null, null, 1033, "Stakeholder")]
		Stakeholder = 1000,
	}
}
#pragma warning restore CS1591
