#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseDataMappingModel
{
	
	
	/// <summary>
	/// Power Pages Component Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum PowerPageComponentType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ad Placement", 21, "#0000ff", "", "", 1033, "Ad Placement")]
		AdPlacement = 26,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Advanced Form", 17, "#0000ff", "", "", 1033, "Advanced Form")]
		AdvancedForm = 19,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Advanced Form Metadata", 19, "#0000ff", "", "", 1033, "Advanced Form Metadata")]
		AdvancedFormMetadata = 21,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Advanced Form Step", 18, "#0000ff", "", "", 1033, "Advanced Form Step")]
		AdvancedFormStep = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Basic Form", 13, "#0000ff", "", "", 1033, "Basic Form")]
		BasicForm = 15,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Basic Form Metadata", 14, "#0000ff", "", "", 1033, "Basic Form Metadata")]
		BasicFormMetadata = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bot Consumer", 22, "#0000ff", "", "", 1033, "Bot Consumer")]
		BotConsumer = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cloud Flow", 28, "#0000ff", "", "", 1033, "Cloud Flow")]
		CloudFlow = 33,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Column Permission", 24, "#0000ff", "", "", 1033, "Column Permission")]
		ColumnPermission = 29,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Column Permission Profile", 23, "#0000ff", "", "", 1033, "Column Permission Profile")]
		ColumnPermissionProfile = 28,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Content Snippet", 6, "#0000ff", "", "", 1033, "Content Snippet")]
		ContentSnippet = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("List", 15, "#0000ff", "", "", 1033, "List")]
		List = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Page Template", 5, "#0000ff", "", "", 1033, "Page Template")]
		PageTemplate = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Poll Placement", 20, "#0000ff", "", "", 1033, "Poll Placement")]
		PollPlacement = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Publishing State", 0, "#0000ff", "", "", 1033, "Publishing State")]
		PublishingState = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Publishing State Transition Rule", 26, "#0000ff", "", "", 1033, "Publishing State Transition Rule")]
		PublishingStateTransitionRule = 31,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Redirect", 25, "#0000ff", "", "", 1033, "Redirect")]
		Redirect = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Shortcut", 27, "#0000ff", "", "", 1033, "Shortcut")]
		Shortcut = 32,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Site Marker", 12, "#0000ff", "", "", 1033, "Site Marker")]
		SiteMarker = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Site Setting", 8, "#0000ff", "", "", 1033, "Site Setting")]
		SiteSetting = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Table Permission", 16, "#0000ff", "", "", 1033, "Table Permission")]
		TablePermission = 18,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UX Component", 29, "#0000ff", "", "", 1033, "UX Component")]
		UxComponent = 34,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web File", 2, "#0000ff", "", "", 1033, "Web File")]
		WebFile = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Link", 4, "#0000ff", "", "", 1033, "Web Link")]
		WebLink = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Link Set", 3, "#0000ff", "", "", 1033, "Web Link Set")]
		WebLinkSet = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Page", 1, "#0000ff", "", "", 1033, "Web Page")]
		WebPage = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Page Access Control Rule", 9, "#0000ff", "", "", 1033, "Web Page Access Control Rule")]
		WebPageAccessControlRule = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Role", 10, "#0000ff", "", "", 1033, "Web Role")]
		WebRole = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Website Access", 11, "#0000ff", "", "", 1033, "Website Access")]
		WebsiteAccess = 12,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Web Template", 7, "#0000ff", "", "", 1033, "Web Template")]
		WebTemplate = 8,
	}
}
#pragma warning restore CS1591
