#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseDataMappingModel
{
	
	
	/// <summary>
	/// Identifies where the social profile originated from, such as Twitter, or FaceBook.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SocialProfile_Community
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Apple Messages For Business", 11, "#0000ff", "", "", 1033, "Apple Messages For Business")]
		AppleMessagesForBusiness = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cortana", 0, "#0000ff", "", "", 1033, "Cortana")]
		Cortana = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Direct Line", 1, "#0000ff", "", "", 1033, "Direct Line")]
		DirectLine = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Direct Line Speech", 3, "#0000ff", "", "", 1033, "Direct Line Speech")]
		DirectLineSpeech = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 4, "#0000ff", "", "", 1033, "Email")]
		Email = 9,
		
		/// <summary>
		/// Facebook item.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Facebook", 15, "", "Facebook item.", "", 1033, "Facebook")]
		Facebook = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Google\'s Business Messages", 12, "#0000ff", "", "", 1033, "Google\'s Business Messages")]
		GoogleSBusinessMessages = 17,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GroupMe", 5, "#0000ff", "", "", 1033, "GroupMe")]
		Groupme = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kik", 6, "#0000ff", "", "", 1033, "Kik")]
		Kik = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Line", 13, "#0000ff", "", "", 1033, "Line")]
		Line = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Microsoft Teams", 2, "#0000ff", "", "", 1033, "Microsoft Teams")]
		MicrosoftTeams = 7,
		
		/// <summary>
		/// Other default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 17, "", "Other default", "", 1033, "Other")]
		Other = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Skype", 8, "#0000ff", "", "", 1033, "Skype")]
		Skype = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Slack", 9, "#0000ff", "", "", 1033, "Slack")]
		Slack = 14,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Telegram", 7, "#0000ff", "", "", 1033, "Telegram")]
		Telegram = 12,
		
		/// <summary>
		/// Twitter.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Twitter", 16, "", "Twitter.", "", 1033, "Twitter")]
		Twitter = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Wechat", 14, "#0000ff", "", "", 1033, "Wechat")]
		Wechat = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("WhatsApp", 10, "#0000ff", "", "", 1033, "WhatsApp")]
		Whatsapp = 15,
	}
}
#pragma warning restore CS1591
