#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseDataMappingModel
{
	
	
	/// <summary>
	/// Post message type private or direct.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SocialActivity_PostMessageType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Private Message", 1, null, null, null, 1033, "Private Message")]
		PrivateMessage = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Public Message", 0, null, null, null, 1033, "Public Message")]
		PublicMessage = 0,
	}
}
#pragma warning restore CS1591
